SELECT *
    FROM EMP
  WHERE ENAME LIKE '%S';
  
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
  
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE SAL > 2000
INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO >= 20;
  
SELECT *
    FROM EMP
  WHERE SAL >= 2000 AND SAL <= 3000;
  
SELECT ENAME, EMPNO, SAL, DEPTNO
    FROM EMP
  WHERE DEPTNO = 30
        AND ENAME LIKE '%E%'
        AND NOT SAL BETWEEN 1000 AND 2000;
        
SELECT *
    FROM EMP
  WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND (JOB = 'MANAGER' OR JOB = 'CLERK')
    AND ENAME NOT LIKE '_L%';