SELECT EMPNO AS EMPLOYEE_NO,
       ENAME AS EMPLOYEE_NAME,
       JOB,
       MGR AS MANAGER,
       HIREDATE,
       SAL AS SALARY,
       COMM AS COMMISION,
       DEPTNO AS DEPARTMENT_NO
       FROM EMP
       
ORDER BY DEPTNO DESC, ENAME ASC;
